jobsboard/config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'jobs#index'

end

jobsboard/app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, presence: true
  validates :company, presence: true
  validates :url, presence: true
end

jobsboard/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

jobsboard/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
 before_action :find_job, only: [:show, :edit, :update, :destroy]

 def index
 	@jobs = Job.all
 end
 
 def show
 end	

 def new
 	@job = Job.new
 end
 
 def create
 	@job = Job.new(job_params)	

 	if @job.save
 		redirect_to @job
 	else
 		@job = Job.new
 	    render :new 
 	end    	
 end

 def edit
 end
 
 def update
 end

 def destroy
 end

 private

 def job_params
   params.require(:job).permit(:title, :description, :company, :url)	
 end

 def find_job
  @job=Job.find(params[:id]) 
 end 

end 


	 

jobsboard/app/helpers/application_helper.rb
module ApplicationHelper
end

jobsboard/app/helpers/jobs_helper.rb
module JobsHelper
end

jobsboard/app/views/jobs/_form.html.erb
<%= simple_form_for(@job, html: {class: 'form-horizontal'}) do |form| %>
  <p>
  <%= form.input :title, label: "Job title" %>
  </p>
  <p>
  <%= form.input :description, label: "Job description" %>
  </p>
  <p>
  <%= form.input :company, label: "Your company" %>
  <p>
  <%= form.input :url, label: "Link to job" %>
  </p>
  <p>
  <%= form.button :submit %>
  </p>
<% end %>

jobsboard/app/views/jobs/index.html.erb
<h1>Rephrase your job ad</h1>

<%= @jobs.each do |job| %>
	<div class = "job">
	<h2>
		<%= link_to job.title, job.url%>
	</h2>
	<p>
		<%= job.company%>
	</p>
	</div>
<% end %>		

<p><%= link_to "Add a job", new_job_path %></p>

 

 

jobsboard/app/views/jobs/new.html.erb
<%= simple_form_for @job do |form| %>
	<p>		
  		<%= form.input :title, label: "Job title" %>
  	</p>

  	<p>
  		<%= form.input :description, label: "Job Description" %>
  	</p>

  	<p>	
  		<%= form.input :company, label: "Your company" %>
  	</p>

  	<p>	
  		<%= form.input :url, label: "Link to job" %>
	</p>

	<p>
  		<%= form.button :submit %>
  	</p>	
<% end %>

jobsboard/app/views/jobs/show.html.erb
<h1>
  <%= @job.title %>
</h1>
<p>
  <%= @job.description %>
</p>	
<p>
  <%= @job.company %>
</p>

<%= link_to "Home", root_path %>

jobsboard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobsboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>